parameters:
  - name: name
    default: Pack_MyGet
  - name: vmImage
    default: ''
  - name: BuildConfiguration
    default: ''
  - name: Workloads
    default: ''

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      BuildConfiguration: ${{ parameters.BuildConfiguration }}
      Workloads: ${{ parameters.Workloads }}
    steps:
      - task: UseDotNet@2
        displayName: Install .NET Core SDK
        inputs:
          useGlobalJson: true
      - task: DotNetCoreCLI@2
        condition: ne(variables.Workloads, '')
        displayName: Install workloads
        inputs:
          command: 'custom'
          custom: 'workload'
          arguments: 'install $(Workloads)'
      - task: PowerShell@2
        displayName: Nuke Target Pack
        inputs:
          targetType: filePath
          filePath: ./build.ps1
          arguments: --target Pack --configuration $(BuildConfiguration) --version-suffix "build$(Build.BuildNumber)"
      - task: PublishBuildArtifacts@1
        displayName: Publish Artifact MyGet
        inputs:
          PathtoPublish: ./artifacts/NuGet
          ArtifactName: MyGet
