parameters:
  - name: name
    default: 'Test_PowerShell'
  - name: vmImage
    default: ''
  - name: BuildConfiguration
    default: ''
  - name: Workloads
    default: ''

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      BuildConfiguration: ${{ parameters.BuildConfiguration }}
      Workloads: ${{ parameters.Workloads }}
    steps:
      - task: UseDotNet@2
        displayName: Install .NET Core SDK
        inputs:
          useGlobalJson: true
      - task: DotNetCoreCLI@2
        condition: ne(variables.Workloads, '')
        displayName: Install workloads
        inputs:
          command: 'custom'
          custom: 'workload'
          arguments: 'install $(Workloads)'
      - task: PowerShell@2
        displayName: Nuke Target Test
        inputs:
          targetType: filePath
          filePath: ./build.ps1
          arguments: --target Test --configuration $(BuildConfiguration) --version-suffix "build$(Build.BuildNumber)"
      - task: PublishTestResults@2
        displayName: Publish Test Results
        inputs:
          testResultsFormat: VSTest
          testResultsFiles: '*.trx'
          searchFolder: $(System.DefaultWorkingDirectory)/artifacts/TestResults
